version: "3.9"
services:
  db:
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}

    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
       - ./init.sql:/docker-entrypoint-initdb.d/1.sql
    networks:
      - app-network

  server: 
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports: 
      - "8080:8080" 
    depends_on:
      - db
    networks:
      - app-network
    restart: on-failure

networks:
  app-network:
    driver: bridge