# Example toml file for database configuration
# Rename this file to 'db.toml' or create a new file
# with the name 'db.toml' in this directory.

DatabaseHost = "Host of your database"
DatabaseName = "Name of your database"
DatabaseUser = "User accessing the database"
DatabasePassword = "Password for database user"
SSLEnabled = false
